### ISSUE TITLE
Wrong colors?

### ISSUE THREAD

**Issue by adfiyo** [Haleth/Aurora#144]
### Description ###

First time using Aurora.
It seems like some colors are off, and are gray for some reason. 

Things Ive noticed(including some pictures).
1. Choosing things like "Dungeon Finder" has a grey highlight instead of the normal yellowish tone.
2. Checkmarks for roles/which dungeons you want to do is grey. Not yellow. 
3. Appearence/transmog tab, has a grey film over all the previews of the skins.

### Steps to Reproduce ###

Install addon 

**Expected behavior:**

Look right.

``` lua
-- If you recived an error, place it here.
```
No errors. 

### Additional information ###

First time using addon. Troubleshooting by turning all the other addons off. 

**Screenshots and GIFs**

![issue1](https://user-images.githubusercontent.com/45051301/48517983-672c4f00-e868-11e8-9ea8-6e624964999d.JPG)
![issue2](https://user-images.githubusercontent.com/45051301/48517984-672c4f00-e868-11e8-9dc0-ec633cea7df0.JPG)

**Installed AddOns:**

Turned all other addons off, still same "problem"

**Comment by Gethe** [comment]
Do you happen to play a priest? Highlights and other accents are generally class colored, which for priests ends up just being grey. You can set a custom highlight color in the options.

**Comment by adfiyo** [comment]
> Do you happen to play a priest? Highlights and other accents are generally class colored, which for priests ends up just being grey. You can set a custom highlight color in the options.

Yeah, upon doing more research It was just me being stupid and activating a custom highlight which happend to be gray.
So that is fixed. But that doesn't explain why xmogs appear "gray" (seen in the photo)

**Comment by Gethe** [comment]
The xmog color (for one you have collected and can use) is technically white, and is applied via the built in 3D light source for each individual model preview. This is a little fiddly since the light actually seen is being "reflected" by the model itself, which can change the perceived color of the light.

The achievements are intended. The colors are based on the default UI, blue for account wide achievements, red for character achievements. No plans to allow users to change this, though I might look at ways to make it less "in your face".
