### ISSUE TITLE
Unmovable icon present in center of screen

### ISSUE THREAD

**Issue by salemlechat** [Haleth/Aurora#154]
The lastest Aurora update causes a square icon of a polearm in the middle of the screen. The icon isn't movable or clickable.

To reproduce:
Update Aurora
Log in

This issue was seen on my account (running Win10) and a friend's account (Mac OS 10.14)

Disabling Aurora removed the icon. Enabling Aurora but unchecking all settings does not.

Screenshot below.
![wowscrnshot_020419_190527](https://user-images.githubusercontent.com/9245202/52251474-01bd8c80-28b2-11e9-985e-fd4b7007a480.jpg)

**Comment by PheoniXi** [comment]
Verbatim after last update

**Comment by stewartqj** [comment]
I see this issue is closed so my comment may not apply, but as of 3:47am EST this issue with the icon is still being experienced across each of my computers using the Aurora Addon.  I assume it will be fixed.  My icon is the DK class icon.  Can’t wait until it’s fixed so I can clock Aurora back on.  Much love.

**Comment by Gethe** [comment]
The fix is out, you'll need to redownload the update.

**Comment by stewartqj** [comment]
Hey Gethe, I get my Aurora from the curse downloader.  I deleted it including saved variables and reinstalled it.  The issue is still occurring.  Any ideas on how to fix?

**Comment by Gethe** [comment]
If reinstalling from the app doesn't work, you should still be able to open the addon website on curse and download it manually.
