### ISSUE TITLE
Classic support?

### ISSUE THREAD

**Issue by Solganis** [Haleth/Aurora#172]
Subject

**Comment by Othra** [comment]
Yes, please. As far as I know currently the only way of achieving transparent panes is going through ElvUI. Having this standalone would be class.

**Comment by Gethe** [comment]
It's in the works, but I can't say when it will be available.

**Comment by Solganis** [comment]
Nice to hear! Thanks!

**Comment by pax0707** [comment]
Just wanted to say that your work is appreciated.
;- )=

**Comment by Solganis** [comment]
@Gethe what about to implement this PR #173 and give us version to test it?

**Comment by Gethe** [comment]
I just pushed a classic branch with updates. An alpha version for classic should be up on curse soon.

**Comment by Dejoule** [comment]
I'm using the alpha, and several aspects work fantastic. I'm using the latest revision available through curse. Current Issues I'm experiencing:

-As of current It only half skins the quest log. It turns text white but the default blizzard frame remains.

-When speaking to a flight master, no image of the continent map loads, it's just a black screen

-The Talent Window is not Skinned at all

-One Request (IF Possible) - when you do address the talent window, can you make it so that all 3 trees are visible in one window instead of having to tab between the 3 and scroll up and down?

Thank you for your work and time! I love what works so far, makes things very clean!

Here is the LUA error that pops:
1x ...Ons\Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:382: attempt to index field 'Bg' (a nil value)
...Ons\Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:382: in function `PortraitFrameTemplateNoCloseButton'
Aurora\Skin\deprecated.lua:446: in function `ReskinPortraitFrame'
Aurora\SkinBlizzard_TradeSkillUI.lua:14: in function `addonModule'
Aurora\Skin\init.lua:222: in function <Aurora\Skin\init.lua:181>
[C]: in function `LoadAddOn'
Skillet-Classic\Skillet-11302.nil.lua:792: in function `DisableBlizzardFrame'
Skillet-Classic\Skillet-11302.nil.lua:1160: in function <Skillet-Classic\Skillet.lua:1082>
[C]: ?
...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-12.lua:70: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:65>
...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-12.lua:527: in function `EnableAddon'
...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0-12.lua:620: in function <...rkInventory\Externals\Ace3\AceAddon\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:380: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:695: in function <FrameXML\UIParent.lua:658>

Locals:
Frame = TradeSkillFrame {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Bg' (a nil value)"
private = <table> {
 isPatch = false
 disabled = <table> {
 }
 uiScale = 1
 API_MINOR = 5
 updateHighlightColor = <function> defined @Aurora\aurora.lua:84
 API_MAJOR = 0
 classColorsHaveChanged = <function> defined @Aurora\aurora.lua:95
 commands = <table> {
 }
 SetupGUI = <function> defined @Aurora\gui.lua:375
 TRIVIAL_QUEST_DISPLAY = "|cffbfbfbf%s (low level)|r"
 OnLoad = <function> defined @Aurora\aurora.lua:38
 Aurora = <table> {
 }
 debug = <function> defined @Aurora\Skin\init.lua:54
 charClass = <table> {
 }
 FRAME_TITLE_HEIGHT = 27
 isLoaded = true
 backdrop = <table> {
 }
 FrameXML = <table> {
 }
 AddOns = <table> {
 }
 UpdateUIScale = <function> defined @Aurora\Skin\api.lua:551
 nop = <function> defined @Aurora\Skin\init.lua:48
 NORMAL_QUEST_DISPLAY = "|cffffffff%s|r"
 classColorsInit = <function> defined @Aurora\aurora.lua:110
 SharedXML = <table> {
 }
 font = <table> {
 }
 classColorsReset = <function> defined @Aurora\Skin\api.lua:734
}
Base = <table> {
 SetHighlight = <function> defined @Aurora\Skin\api.lua:487
 GetSkinList = <function> defined @Aurora\Skin\api.lua:55
 SetTexture = <function> defined @Aurora\Skin\api.lua:529
 CreateBackdrop = <function> defined @Aurora\Skin\api.lua:394
 SetBackdrop = <function> defined @Aurora\aurora.lua:149
 CreateColor = <function> defined @Aurora\Skin\api.lua:648
 Post = <table> {
 }
 IsTextureRegistered = <function> defined @Aurora\Skin\api.lua:525
 RegisterTexture = <function> defined @Aurora\Skin\api.lua:539
 CropIcon = <function> defined @Aurora\Skin\api.lua:69
 Pre = <table> {
 }
 AddSkin = <function> defined @Aurora\Skin\api.lua:44
 SetFont = <function> defined @Aurora\Skin\api.lua:416
 SetBackdropColor = <function> defined @Aurora\Skin\deprecated.lua:44

**Comment by Gethe** [comment]
Yeah my character is only level 8 at the moment. I'll update as I level up. Thanks for the feedback.

**Comment by pax0707** [comment]
On stables, hunter pet model is blown to screen size.

**Comment by Dejoule** [comment]
Not a problem. I try my best to provide useful information rather than get upset because it doesn't work.

**Comment by MisatoTremor** [comment]
@Gethe Please check my PR, the components named by @Dejoule are working there (all major UI elements do).

**Comment by Solganis** [comment]
Yep, would be great to try this fixes. Ready to test on the weekends.

**Comment by Dejoule** [comment]
@MisatoTremor - I downloaded your version. It doesn't skin the social window at all. It does skin everything else. (I tested this with no other addons.) so that is the only issue I can identify at this time with that code. which just leaves feature requests.

All 3 skill trees displayed at once in the talent window
Compatibility with at least one of the 2 panel quest logs.  (QuestGuru, QuestLog Extended, or Wide Quest Log) - Wide Quest Log is almost completely skinned with the version from the PR.

![image](https://user-images.githubusercontent.com/54760670/65377546-50157500-dc62-11e9-86df-6a1f9da2c52e.png)

![image](https://user-images.githubusercontent.com/54760670/65377535-383df100-dc62-11e9-9ef5-7a4838f10568.png)

**Comment by MisatoTremor** [comment]
There is an error I didn't get before, going to fix it. Social and Flight Master windows are skinned, the addon just does not reach them because of that error. The requested Talent redesign is not easily possible because of how that window works and - just like skinning some other AddOns windows - might be out of scope of this AddOn.

**Comment by Dejoule** [comment]
understood. I'm not a coder, so all I can do is ask

**Comment by MisatoTremor** [comment]
Updated my version.

**Comment by Solganis** [comment]
@MisatoTremor tried you're version

Talent tree is way too big now. Dunno about that is normal, or not. Personally - I don't like it.
![image](https://user-images.githubusercontent.com/44605445/65380245-9826ad00-dcdf-11e9-978a-b23506997a4a.png)
Quest log have some Blizz UI and fonts are too dark
![image](https://user-images.githubusercontent.com/44605445/65380248-bd1b2000-dcdf-11e9-88b0-fbd6c646fdd1.png)
Character screen now doesn't have a skin 
![image](https://user-images.githubusercontent.com/44605445/65380253-db811b80-dcdf-11e9-9d17-295001c6a614.png)

Also, getting an error when log into the game, don't know if this related
`Date: 2019-09-22 02:24:39
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Aurora\test.lua line 7:
   Usage: NonEmptyItem:ContinueOnLoad(callbackFunction)
Debug:
   [C]: error()
   ..\FrameXML\ObjectAPI\Item.lua:235: ContinueOnItemLoad()
   Aurora\test.lua:7: in main chunk
Locals:
(*temporary) = "Usage: NonEmptyItem:ContinueOnLoad(callbackFunction)"

AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ACP, v3.5.6 
  AdvancedInterfaceOptions, v1.3.2
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasTransportation, vv1.45.00.11302.00
  AtlasLootClassic, vv1.1.12
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6420 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Aurora, v8.1.0.4
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_ruRU v1.13.2.11302 <none>
  (ck=2fb)

`

**Comment by MisatoTremor** [comment]
When using the version directly from repository, remove the following lines from Aurora.toc. That should fix the error / not skinned windows:
```toc
#@do-not-package@
test.lua
#@end-do-not-package@
```
You are also using a Quest log AddOn, which propably alters the window in a way that interferes with Aurora.
As for the talents that's still on my improvements todo. :-D

**Comment by Solganis** [comment]
@MisatoTremor Thanks for you're work and clarification!
Some more problems with latest Alpha, downloaded through Curse.

- Guild tab have some Blizz UI
https://i.gyazo.com/590e36f00cef7df66716e916fbaf24bd.png

- Raid tab have some Blizz UI
https://i.gyazo.com/04e7a949559fbf38af6b26e1209d9bfc.png

- Mailbox have unadjusted icon
https://i.gyazo.com/ef203c92d64706a48d0c4d456ff2d9e6.png

Wishlist:

- Can we skin frame that tells us how much air we have left? it's pretty niche, but still
https://i.gyazo.com/5b3f89306cf94b62d60e18a91b18b909.png

**Comment by MisatoTremor** [comment]
Please also note that the Alpha available from Curse and my version are different ones :-)

**Comment by Solganis** [comment]
@MisatoTremor Oh, sorry! I thought that I starting to understand something about GitHub, but no :D 

@Gethe is there a need to report Issues? If yes, is that thread is a place for it? Or make new ones like I report above?

**Comment by Gethe** [comment]
Lets keep them on this thread for now.

**Comment by yuanalexwu** [comment]
Done yet?

**Comment by Solganis** [comment]
Dear @Gethe, can you please update your gorgeous addon?
After 1.13.3 update some of the windows are broken :( 

Issues:
- Dialogue window now doesn't have a skin
https://i.gyazo.com/ca0222587fb9e35e7f8a3bd4e9249180.png

- Mail window
https://i.gyazo.com/97503027f5d870ece560b00cf238bcd8.png

- Honor window
https://i.gyazo.com/69ea91822faba85b4d966e842d9d22bd.png

- Error when logging in
`Date: 2019-12-15 18:33:24
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Aurora\Skin\deprecated.lua line 152:
   attempt to index local 'f' (a nil value)
Debug:
   Aurora\Skin\deprecated.lua:152: Reskin()
   Aurora\Skin\FrameXML\HelpFrame.lua:93: ?()
   Aurora\Skin\init.lua:203:
      Aurora\Skin\init.lua:181
Locals:
f = nil
noHighlight = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'f' (a nil value)"
Base = <table> {
 SetHighlight = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:492
 GetSkinList = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:55
 SetTexture = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:536
 CreateBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:394
 SetBackdrop = <function> defined @Interface\AddOns\Aurora\aurora.lua:149
 CreateColor = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:655
 Post = <table> {
 }
 IsTextureRegistered = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:532
 RegisterTexture = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:546
 CropIcon = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:69
 Pre = <table> {
 }
 AddSkin = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:44
 SetFont = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:416
 SetBackdropColor = <function> defined @Interface\AddOns\Aurora\Skin\deprecated.lua:44
}
Color = <table> {
 highlight = <table> {
 }
 cyan = <table> {
 }
 Lightness = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:635
 grayLight = <table> {
 }
 ruby = <table> {
 }
 Saturation = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:627
 button = <table> {
 }
 Post = <table> {
 }
 orange = <table> {
 }
 red = <table> {
 }
 Hue = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:612
 magenta = <table> {
 }
 blue = <table> {
 }
 lime = <table> {
 }
 frame = <table> {
 }
 white = <table> {
 }
 Create = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:655
 jade = <table> {
 }
 grayDark = <table> {
 }
 violet = <table> {
 }
 black = <table> {
 }
 green = <table> {
 }
 Pre = <table> {
 }
 yellow = <table> {
 }
 marine = <table> {
 }
 gray = <table> {
 }
}

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  ACP, v3.5.6-2-g9b55b72 
  AdvancedInterfaceOptions, v1.3.3-3-g58f2fa4
  AtlasLootClassic, vv1.4.2
  AtlasLootClassicData, vv1.4.2
  AtlasLootClassicDungeonsAndRaids, vv1.4.2
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  Aurora, v8.2.0.2
  LibSharedMedia30, v3.0-113
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_ruRU v1.13.3.11303 <none>
  (ck=2f8)
`

**Comment by Solganis** [comment]
@Gethe 

M'lord?

**Comment by Havenloft** [comment]
I'm getting the same error on Classic as Solganis.
After reading this thread.. Am I to understand that we are supposed to be using @MisatoTremor version of the Classic addon now? I'm confused.

**Comment by Solganis** [comment]
> 
> 
> I'm getting the same error on Classic as Solganis.
> After reading this thread.. Am I to understand that we are supposed to be using @MisatoTremor version of the Classic addon now? In which case I'm not entirely sure how to find that version. I'm confused.

Nope. Use Alpha one from Gethe.

**Comment by Gethe** [comment]
Got a new alpha build on curse. Still a few more things to do, but it should be better. https://www.curseforge.com/wow/addons/aurora/files

**Comment by Solganis** [comment]
@Gethe 
Oh my gooooooood
Let me hug you

**Comment by Gethe** [comment]
Classic support is now officially out there on both Curse and WoWInterface. Please be sure to note that you are on Classic when submitting a new issue.
